owner: solbra
repo: status

sites:
  - name: Solbra
    url: https://solbra.com.br
  - name: Olha Meu Link
    url: https://olhameu.link
  - name: ApoioGenealogi.co
    url: https://apoiogenealogi.co

status-website:
  baseUrl: /
  logoUrl: https://plataforma.solbra.com.br/assets/images/solbra-dark.svg
  name: Solbra
  introTitle: 'Operação dos Sistemas'
  introMessage: 'Essa página mostra atualizações sobre a operação dos sistemas Solbra.'
  navbar:
    - title: Status
      href: /
